apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ca-org1-example-com
  name: ca-org1-example-com
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ca-org1-example-com
    spec:
      hostAliases:
        - ip: '127.0.0.1'
          hostnames:
            - 'ca.org1.example.com'
        # - ip: '172.17.0.12'
        #   hostnames:
        #     - 'orderer.example.com'
        - ip: '172.17.0.10'
          hostnames:
            - 'couchdb'
      containers:
        - args:
            # - sleep
            # - '3600'
            - sh
            - -c
            - fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
              --ca.keyfile /etc/hyperledger/fabric-ca-server-config/19ab65abbb04807dad12e4c0a9aaa6649e70868e3abd0217a322d89e47e1a6ae_sk
              -b admin:adminpw -d
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca.org1.example.com
          image: hyperledger/fabric-ca:1.2.1
          name: ca-org1-example-com
          ports:
            - containerPort: 7054
          resources: {}
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: ca-org1-example-com-claim0
      restartPolicy: Always
      volumes:
        - name: ca-org1-example-com-claim0
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer/crypto-config/peerOrganizations/org1.example.com/ca
          # persistentVolumeClaim:
          #   claimName: ca-org1-example-com-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ca-org1-example-com
  name: ca-org1-example-com
spec:
  ports:
    - name: '7054'
      port: 7054
      targetPort: 7054
  selector:
    io.kompose.service: ca-org1-example-com
status:
  loadBalancer: {}
