apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
        tier: backend
        track: stable
    spec:
      hostAliases:
        - ip: '172.17.0.9'
          hostnames:
            - 'peer0.org1.example.com'
        - ip: '172.17.0.4'
          hostnames:
            - 'ca.org1.example.com'
        - ip: '172.17.0.7'
          hostnames:
            - 'orderer.example.com'
        - ip: '172.17.0.10'
          hostnames:
            - 'couchdb'
      containers:
        - name: cli
          image: 'hyperledger/fabric-tools:1.2.1'
          tty: true
          stdin: true
          env:
            - name: GOPATH
              value: '/opt/gopath'
            - name: CORE_LOGGING_GOSSIP
              value: 'INFO'
            - name: CORE_LOGGING_PEER
              value: 'DEBUG'
            - name: CORE_PEER_ID
              value: 'peer0.org1.example.com'
            - name: CORE_PEER_ADDRESS
              value: 'peer0.org1.example.com:7051'
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 'peer0.org1.example.com:7053'
            - name: CORE_PEER_LOCALMSPID
              value: 'Org1MSP'
            - name: CORE_PEER_TLS_ENABLED
              value: 'false'
            - name: CORE_PEER_MSPCONFIGPATH
              value: '/opt/gopath/src/github.com/chaincode/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp'
          workingDir: /opt/gopath/src/github.com/chaincode
          command: ['/bin/bash', '-c']
          args:
            [
              'cp -r chaincode_example02/ $GOPATH/src; apt-get update && apt-get install -y iputils-ping; sleep 48h;',
            ]
          volumeMounts:
            # - name: crypto-config
            #   mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
            # - name: channel-artifacts
            #   mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
            - name: chaincode
              mountPath: /opt/gopath/src/github.com/chaincode
            - name: host
              mountPath: /host/var/run/
      volumes:
        # - name: crypto-config
        #   hostPath:
        #     path: /home/mini01/WS/fabric-kub/network/crypto-config
        # - name: channel-artifacts
        #   hostPath:
        #     path: /home/mini01/WS/fabric-kub/network/channel-artifacts
        - name: chaincode
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer
        - name: host
          hostPath:
            path: /var/run/
