apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: orderer-example-com
  name: orderer-example-com
spec:
  ports:
  - name: "7050"
    port: 7050
    targetPort: 7050
  selector:
    io.kompose.service: orderer-example-com
status:
  loadBalancer: {}
