apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: orderer-example-com
  name: orderer-example-com
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: orderer-example-com
    spec:
      hostAliases:
        - ip: '127.0.0.1'
          hostnames:
            - 'orderer.example.com'
        - ip: '172.17.0.4'
          hostnames:
            - 'ca.org1.example.com'
        - ip: '172.17.0.10'
          hostnames:
            - 'couchdb'
      containers:
        - args:
            - orderer
          env:
            - name: ORDERER_GENERAL_GENESISFILE
              value: /etc/hyperledger/configtx/composer-genesis.block
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /etc/hyperledger/msp/orderer/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_LOGLEVEL
              value: debug
          image: hyperledger/fabric-orderer:1.2.1
          name: orderer-example-com
          ports:
            - containerPort: 7050
          resources: {}
          volumeMounts:
            - mountPath: /etc/hyperledger/configtx
              name: orderer-example-com-claim0
            - mountPath: /etc/hyperledger/msp/orderer/msp
              name: orderer-example-com-claim1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      restartPolicy: Always
      volumes:
        - name: orderer-example-com-claim0
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer
        - name: orderer-example-com-claim1
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: orderer-example-com
  name: orderer-example-com
spec:
  ports:
    - name: '7050'
      port: 7050
      targetPort: 7050
  selector:
    io.kompose.service: orderer-example-com
status:
  loadBalancer: {}
