apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ca-org1-example-com
  name: ca-org1-example-com
  namespace: org1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: ca-org1-example-com
    spec:
      containers:
        - args:
            # - sleep
            # - '3600'
            - sh
            - -c
            - fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1-cert.pem
              --ca.keyfile /etc/hyperledger/fabric-ca-server-config/bd166265e28ac66b81e564aacd88657a538ef74d8b0b7856319b6ae32c89ca47_sk
              -b admin:adminpw -d
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-org1-example-com
            - name: GODEBUG
              value: 'netdns=go'
          image: hyperledger/fabric-ca:1.4.0
          name: ca-org1-example-com
          ports:
            - containerPort: 7054
          resources: {}
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: peer-ca
      restartPolicy: Always
      volumes:
        - name: peer-ca
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer/crypto-config/peerOrganizations/org1/ca
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ca-org1-example-com
  name: ca-org1-example-com
  namespace: org1
spec:
  ports:
    - name: '7054'
      port: 7054
      targetPort: 7054
  selector:
    io.kompose.service: ca-org1-example-com
status:
  loadBalancer: {}
