apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cli
  name: cli
  namespace: org1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
        tier: backend
        track: stable
    spec:
      containers:
        - name: cli
          image: 'hyperledger/fabric-tools:1.4.0'
          tty: true
          stdin: true
          env:
            - name: GOPATH
              value: '/opt/gopath'
            - name: CORE_LOGGING_GOSSIP
              value: 'INFO'
            - name: CORE_LOGGING_PEER
              value: 'DEBUG'
            - name: CORE_PEER_ID
              value: 'peer0.org1'
            - name: CORE_PEER_ADDRESS
              value: 'peer0.org1:7051'
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 'peer0.org1:7053'
            - name: CORE_PEER_LOCALMSPID
              value: 'Org1MSP'
            - name: CORE_PEER_TLS_ENABLED
              value: 'false'
            - name: CORE_PEER_MSPCONFIGPATH
              value: '/opt/gopath/src/github.com/chaincode/crypto-config/peerOrganizations/org1/users/Admin@org1/msp'
            - name: GODEBUG
              value: netdns=go
          workingDir: /opt/gopath/src/github.com/chaincode
          command: ['/bin/bash', '-c']
          args: [
              'cp -r chaincode_test/ $GOPATH/src;
              apt-get update && apt-get install -y iputils-ping;
              sleep 48h;',
            ]
          volumeMounts:
            # bash ./k8s/v2/install.sh
            - name: chaincode
              mountPath: /opt/gopath/src/github.com/chaincode
            - name: fabric
              mountPath: /opt/gopath/src/github.com/hyperledger/fabric
            # - name: host
            #   mountPath: /host/var/run/
      volumes:
        - name: chaincode
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer
        - name: fabric
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer/fabric-release-1.4
        # - name: host
        #   hostPath:
        #     path: /var/run/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-server
  name: node-server
  namespace: org1
spec:
  type: NodePort
  ports:
    - name: 'node-server'
      port: 8889
      targetPort: 8889
      nodePort: 30001
  selector:
    app: cli
