apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
  name: couchdb
  namespace: org1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: couchdb
    spec:
      containers:
        - env:
            - name: DB_URL
              value: http://localhost:5984/member_db
          image: hyperledger/fabric-couchdb:0.4.10
          name: couchdb
          ports:
            - containerPort: 5984
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
  name: couchdb
  namespace: org1
spec:
  type: NodePort
  ports:
    - name: '5984'
      port: 5984
      targetPort: 5984
      nodePort: 30005
  selector:
    io.kompose.service: couchdb
status:
  loadBalancer: {}
