apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: peer0-org1-example-com
  name: peer0-org1-example-com
  namespace: org1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: peer0-org1-example-com
    spec:
      containers:
        - name: peer1-org1
          image: hyperledger/fabric-peer:1.4.0
          env:
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: CouchDB
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: couchdb:5984
            - name: CORE_VM_ENDPOINT
              value: tcp://172.17.0.1:2376
            # - name: CORE_VM_ENDPOINT
            #   value: 'unix:///host/var/run/docker.sock'
            - name: FABRIC_LOGGING_SPEC
              value: 'DEBUG'
            - name: CORE_PEER_TLS_ENABLED
              value: 'false'
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: 'true'
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: 'false'
            - name: CORE_PEER_PROFILE_ENABLED
              value: 'true'
            - name: CORE_PEER_TLS_CERT_FILE
              value: '/etc/hyperledger/fabric/tls/server.crt'
            - name: CORE_PEER_TLS_KEY_FILE
              value: '/etc/hyperledger/fabric/tls/server.key'
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: '/etc/hyperledger/fabric/tls/ca.crt'
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: 'true'
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: '0.0.0.0:7052'
            - name: CORE_PEER_ID
              value: peer1.org1
            - name: CORE_PEER_ADDRESS
              value: peer0.org1:7051
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0.org1:7051
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer0.org1:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0.org1:7051
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/peer/msp
            - name: ORDERER_URL
              value: orderer.orderer-org:7050
            - name: GODEBUG
              value: 'netdns=go'
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
          command: ['bash', '-c']
          args: [
              '
              peer node start --peer-chaincodedev=true
              ',
            ]
          volumeMounts:
            # - mountPath: /host/var/run/
            #   name: run-path
            - mountPath: /etc/hyperledger/configtx
              name: configtx-path
            - mountPath: /etc/hyperledger/peer/msp
              name: peer-msp
            - mountPath: /etc/hyperledger/msp/users
              name: peer-user-path
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      volumes:
        # - name: run-path
        #   hostPath:
        #     path: /var/run/
        - name: configtx-path
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer
        - name: peer-msp
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer/crypto-config/peerOrganizations/org1/peers/peer0.org1/msp
        - name: peer-user-path
          hostPath:
            path: /Users/bangqchi/Programming/Blockchain/fabric-dev-servers/fabric-scripts/hlfv12/composer/crypto-config/peerOrganizations/org1/users
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: peer0-org1-example-com
  name: peer0
  namespace: org1
spec:
  selector:
    io.kompose.service: peer0-org1-example-com
  type: NodePort
  ports:
    - name: externale-listen-endpoint
      protocol: TCP
      port: 7051
      targetPort: 7051
      nodePort: 30004

    - name: chaincode-listen
      protocol: TCP
      port: 7052
      targetPort: 7052
      nodePort: 30009

    - name: event-listen
      protocol: TCP
      port: 7053
      targetPort: 7053
      nodePort: 30006
